### ISSUE TITLE
Step 1: Render Full Maximum Intensity

### ISSUE THREAD

**Issue by TingTingShao** [DanuserLab/u-track3D#1]
Hi, 

I used the frames.gif image as input, selected via Import Movie using Bioformat. After selection, there are three channels diaplayed under panel. I moved on to -Step 1: Render Full Maximum Intensity, apply the default setting, but error shows: Index exceeds the number of array elements. Index must not exceed 1.  I wonder what is the image you used in the example, and what caused this error. For low quality image, is it possible to analyze with this software?

Thanks,
tingting

**Comment by DanuserLab** [comment]
Thank you for trying out u-track3D and for reporting this issue.

Please make sure that you are using a Bioformat-compatible image as input. You can refer to the example datasets provided in the README at the following section: [u-track3D description-of-example-datasets](https://github.com/DanuserLab/u-track3D#description-of-example-datasets). The [README](https://github.com/DanuserLab/u-track3D#readme) also provides detailed instructions and information of this package. Thank you.
